Initialized binary tree implementation
snippetsx/algorithms_and_structures pull request #4
Opened 2023-09-13 06:57 UTC by snippetsx

Minimal b_tree realization

2023-09-13 07:06 UTC, justas05 requested changes

2023-09-13 07:06 UTC, justas05 commented on b_tree.h
> +int b_search(btree_t **root, int value);
В конце файла надо ставить пустую строку!

2023-09-13 07:06 UTC, justas05 commented on b_tree.h
> +void bfs(btree_t *root);
Эта функция не должна была оказаться в заголовочном файле

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +  temp->key = item;
Чтобы выполнять присваивание, нужно убедиться, что память была выделена!

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +// stdin
Это в коммит не нужно было отправлять. Оно не относится к дереву.

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +btree_t *queue[100];
Этот код был исключительно для проверки. Его не надо включать в коммит.

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +    // int inserted = 0;
Лишние комментарии

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +    if (!(node = b_new_node(key)))
Здесь условие всегда ложное, т.к. программа упадет, если память не выделится

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +    while(walker->left)
Функция не до конца проверена...

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +    while(walker->right)
аналогично

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +    while(walker){
Поторопился в написании этого цикла.
Функция не до конца проверена...

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +
Лишняя пустая строка

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +            return 1;
Почему возвращается int? Подумай, что пользователь хотел бы от этой функции получить.

2023-09-13 07:06 UTC, justas05 commented on b_tree.c
> +            continue;
Зачем?..

2023-09-29 12:25 UTC, snippetsx commented on b_tree.c
> +    if (!(node = b_new_node(key)))
Так это мы вместе с вами писали

2023-10-02 07:26 UTC, justas05 requested changes

2023-10-02 07:26 UTC, justas05 commented on test_b_tree.c
> +int main()
Фукнция должна называться иначе

2023-10-02 07:26 UTC, justas05 commented on b_tree.c
> +btree_t *b_search(btree_t *root, int value) //Почти бинпоиск. Если элемент существует, выведет 1, иначе 0
Комментарий здесь лишний и не совсем корректный

2023-10-02 20:05 UTC, justas05 approved these changes

2023-10-03 06:28 UTC, merged